# Generated by Django 5.2.6 on 2025-09-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0003_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Category',
            new_name='category',
        ),
    ]
