# Generated by Django 5.2.6 on 2025-09-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0004_rename_category_recipe_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
