# Generated by Django 5.2.6 on 2025-09-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0005_delete_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
